---
title: "Intro to Fred Hutch Cluster Computing"
date: "`r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: Description about Course/Book.
favicon: assets/favicon.ico
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), "bookdown", "knitr", "rmarkdown"
), "packages.bib")
```

# About this Course {-}

Fred Hutch maintains a [high performance computing cluster](https://en.wikipedia.org/wiki/HPCC) specifically to support work that requires intensive computing. The Fred Hutch cluster (sometimes called "Rhino" and/or "Gizmo") allow you to do more than your average desktop computer can handle.

Our goal for this course is to get you running on the Fred Hutch cluster **quickly and efficiently**. It is intended for everyone from brand new cluster users to researchers who have used a cluster at another institution but are new to Fred Hutch. We hope that the following modules will help you take advantage of the powerful resources the Fred Hutch has to offer!

The Fred Hutch cluster is supported by a group in IT called Scientific Computing, and this course was developed by the Fred Hutch Data Science Lab in collaboration with them. Please see the [author credits](#about-the-authors) for more information.